version: 2
updates:
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, python]
  - package-ecosystem: pip
    directory: /functions/realtime-notifier
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, python]
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, javascript]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, github-actions]
  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, terraform]
